version: '2'
services:
    web:
        build: ./flask-api
        ports: 
            - "5000:5000"
        volumes: 
            - .:/usr/src/app/
        depends_on:
            - redis
    redis:
        image: redis